In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

1.13.0+cu116


To import pytorch this is the method which is supposed to be used Pytorch tensors are created using Torch.tensors()


In [ ]:
### Introduction to Tensors

Tensors are the way to represent Numeric Data 
#Creating Tensors


In [ ]:
scalar=torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
Vector=torch.tensor([7,7])
Vector

tensor([7, 7])

Vector has magnitude and Direction

In [ ]:
Vector.ndim

1

In [ ]:
Vector.shape

torch.Size([2])

In [ ]:
#Matrix

In [ ]:
Matrix=torch.tensor([[7,8],[1,2]])

In [ ]:
Matrix

tensor([[7, 8],
        [1, 2]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1]

tensor([1, 2])

In [ ]:
Matrix.shape

torch.Size([2, 2])

#Tensor

In [ ]:
Tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
Tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
Tensor.ndim

2

In [ ]:
Tensor.shape

torch.Size([3, 3])

In [ ]:
###Random Tensors

###Random Tensors
why Random Tensors?
Random tensors are important because the way many neural netwroks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
Start with random numbers->Look at data-> update random Numbers->Look at data->Update Random Numbers

In [ ]:
#Creating random Tensor of size (3,4)

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4275, 0.6815, 0.0321, 0.8154],
        [0.4614, 0.4644, 0.5026, 0.4436],
        [0.9611, 0.5521, 0.9970, 0.1859]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creating a random tensor with similar shape to an Image tensor
random_image_size_tensor=torch.rand(size=(3,224,224))

In [ ]:
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

For an image seperate the color channels with the Image Of 3 different colors namingly rgb And then with the [color_channels,height,width] split the Image

In [ ]:
###Zeroes and Ones

In [ ]:
zero=torch.zeros(size=(3,4))

In [ ]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(4,5))

In [ ]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
###Creating a range of Tensors

In [ ]:
#Use torch.range()

In [ ]:
torch.range(0,10)

<ipython-input-252-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.__version__

'1.13.0+cu116'

In [ ]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating a range of tensors
one_to_ten=torch.arange(start=1,end=10,step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeroes=torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

For torch range Creates range of nos while Torch.arange creates a range of numbers from start to end 


###Tensor Datatypes

Issues because of datatype:


1.   Tensors are not right data type
2.   Tensors are not of right shape
3.   Tensors are not of right device 


In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
some_tensor=torch.rand(3,4)

In [ ]:
some_tensor

tensor([[0.4416, 0.1231, 0.4581, 0.6558],
        [0.8750, 0.4786, 0.6904, 0.3495],
        [0.7960, 0.3141, 0.9659, 0.1459]])

In [ ]:
some_tensor.shape,some_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.4416, 0.1231, 0.4581, 0.6558],
        [0.8750, 0.4786, 0.6904, 0.3495],
        [0.7960, 0.3141, 0.9659, 0.1459]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


### Manipulating Tensor Operations


*   Addition
*   Multiplication
*   Subraction
*   Division
*   Matrix Multiplication




In [ ]:
#Create a tensor
tensor=torch.tensor([1,2,3])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

Two ways of Performing Matrix Multiplication in neural networks and Deep Learning:
1.  ELement-wise multiplication
2.  Matrix Multiplication(dot product)

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#Element wise Multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time 
value=0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 685 µs, sys: 0 ns, total: 685 µs
Wall time: 694 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 41.5 µs


tensor(14)

In [ ]:

tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,8],[9,10],[11,12]])
#torch.matmul(tensor_A,tensor_B)

Transpose fixes the Axes of the given tensor 

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

###Tensor Aggregation

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the Min
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the Positiional Min and Max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()
#Arg min will return the index value of The minimum element in the tensor 

tensor(0)

In [ ]:
x.argmax()

tensor(9)

*  Reshaping-reshapes an input tensor to a defined shape 
*  View-a view of an input tensor of certain shape but keep the same memory as the original tensor
*  Stacking- combines multiple tensors on top of each other (vstack) combines multiple tensors on side by side (hstack)
*  Squeeze -removes all `1` dimensions from a tensor 
*  Unsaqueeze- add `1` dimensions to a target tensor 
*  Permute-Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x=torch.arange(1.,10.)

In [ ]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#x_reshaped=x.reshape(1,7)
## It is not possible to squeeze a tensor using reshape method 
x_reshaped=x.reshape(3,3)

In [ ]:
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x (because a view of tensor shares the same memory as yhe original)

In [ ]:

z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other 
x_stacked=torch.stack([x,x,x,x],dim=0)

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)

In [ ]:
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#v stack is dim is equals to 0
#h stack is dim is equal to 1
z.shape

torch.Size([1, 9])

In [ ]:
#torch.squeeze()-removes all single dimensions from a target tensor
print(f"Previous tensor:{z}")
print(f"Previous tensor:{z.shape}")
#Remove extra dimensions from x_reshaped
x_squeezed=z.squeeze()
print(f"New Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor:torch.Size([1, 9])
New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.squeeze()-adds single dimension to a target tensor
print(f"Previous tensor:{x}")
print(f"Previous tensor:{x.shape}")
#Adds extra dimensions from x
x_unsqueezed=x.unsqueeze(dim=0)
print(f"New Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#if Dim is equals to 1 Then it becomes 9*1

Previous tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous tensor:torch.Size([9])
New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


### Permute

In [ ]:
# torch.permute-rearranges the dimensions of a target tensor in a specific order
x_original=torch.rand(size=(224,224,3))
#[height,width,colour_channels]
#Permute the Original Tensor to rearrange the axis(or Dim) order
x_permute=x_original.permute(2,0,1) #Shifts axis 0->1 1->2 2->0

print(f"Previous_shape:{x_original.shape}")
print(f"New_shape:{x_permute.shape}")

Previous_shape:torch.Size([224, 224, 3])
New_shape:torch.Size([3, 224, 224])


In [ ]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [ ]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permute[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (Selecting data from tensors)

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)

In [ ]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
#Lets index on our new Tensor

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#When DIm =2

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
#you can also use ":" to select "all" of a target Dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and let dimensions but only index 1 of 2nd Dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0th Dimension but only the 1 index value of 1st and 2nd Dimension
x[:,1,1]

tensor([5])

In [ ]:
#Pytorch Tensors and Numpy 



Numpy is a popular scientific Python Numerical COmputing Library 
And because of this Pytorch has the functionality to Interact with it .


In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
array=np.arange(1.0,8.0)

In [ ]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:

tensor=torch.from_numpy(array).type(torch.float32)

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to Numpy

In [ ]:
ternsor=torch.ones(7)

In [ ]:
numpy_tensor=ternsor.numpy()

In [ ]:
ternsor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility(Taking Random out of Random)
 * In Short How a Neural Network learns 
 * To reduce the Randomness in neural networks and Pytorch comes the concept of A **random seed**.
 * Essentialy what the random seeds does is the Flavour the Randomness


In [ ]:
random_tensor_A=torch.rand(3,4)

In [ ]:
random_tensor_B=torch.rand(3,4)

In [ ]:
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.7596, 0.5852, 0.2558, 0.2467],
        [0.6920, 0.2429, 0.6962, 0.7846],
        [0.1366, 0.0064, 0.8689, 0.1689]])
tensor([[0.9076, 0.1583, 0.4083, 0.1810],
        [0.0035, 0.9562, 0.7337, 0.0302],
        [0.7263, 0.8465, 0.3106, 0.7769]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
Random_Seed=42

In [ ]:
torch.manual_seed(Random_Seed)

In [ ]:
torch.manual_seed(Random_Seed)
random_tensor_C=torch.rand(3,4)

In [ ]:
torch.manual_seed(Random_Seed)
random_tensor_D=torch.rand(3,4)

In [ ]:
print(random_tensor_C)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
